platform :ios, '7.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'SystemServices', '~> 1.1.0'
pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.4.1'
pod 'BlocksKit', '~> 2.2.5'
pod 'YYModel', '~> 1.0.2'
pod 'JHChainableAnimations', '~> 1.3.0'
